# Generated by Django 4.1.7 on 2023-03-10 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_teacher_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teacher_name',
            new_name='teacher',
        ),
    ]
